package com.planimrt.model;

public enum EventType {
    USER_LOGIN,
    USER_LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_DELETED,
    DICOM_UPLOADED,
    DICOM_PROCESSED,
    DICOM_DELETED,
    MCS_CALCULATED,
    PLOT_GENERATED,
    ERROR_OCCURRED,
    SYSTEM_ERROR
}